import type { AccessState, DesktopSnapshot } from "./contracts";

const providers: DesktopSnapshot["providers"] = [
  {
    id: "codex",
    name: "OpenAI Codex",
    kind: "agent",
    protocol: "Plugin",
    tier: "first_class",
    state: "connected",
    detail: "Handshake MCP válido",
  },
  {
    id: "claude",
    name: "Claude Code",
    kind: "agent",
    protocol: "MCP",
    tier: "first_class",
    state: "needs_attention",
    detail: "Configuração encontrada; app ausente",
  },
  {
    id: "vscode",
    name: "VS Code",
    kind: "editor",
    protocol: "MCP",
    tier: "first_class",
    state: "detected",
    detail: "Editor encontrado",
  },
  {
    id: "cursor",
    name: "Cursor",
    kind: "editor",
    protocol: "MCP",
    tier: "first_class",
    state: "not_installed",
    detail: "Não encontrado neste Mac",
  },
  {
    id: "windsurf",
    name: "Windsurf",
    kind: "editor",
    protocol: "MCP",
    tier: "first_class",
    state: "not_installed",
    detail: "Não encontrado neste Mac",
  },
  {
    id: "kiro",
    name: "Kiro",
    kind: "editor",
    protocol: "MCP",
    tier: "first_class",
    state: "not_installed",
    detail: "Não encontrado neste Mac",
  },
  {
    id: "jetbrains",
    name: "JetBrains",
    kind: "editor",
    protocol: "MCP",
    tier: "first_class",
    state: "not_installed",
    detail: "Não encontrado neste Mac",
  },
  {
    id: "zed",
    name: "Zed",
    kind: "editor",
    protocol: "MCP",
    tier: "first_class",
    state: "not_installed",
    detail: "Não encontrado neste Mac",
  },
  {
    id: "gemini",
    name: "Gemini CLI",
    kind: "agent",
    protocol: "CLI",
    tier: "compatible",
    state: "not_installed",
    detail: "CLI não encontrada",
  },
  {
    id: "opencode",
    name: "OpenCode",
    kind: "agent",
    protocol: "CLI",
    tier: "compatible",
    state: "detected",
    detail: "CLI encontrada",
  },
  {
    id: "grok",
    name: "Grok",
    kind: "agent",
    protocol: "MCP",
    tier: "compatible",
    state: "detected",
    detail: "CLI e rota local encontradas",
  },
  {
    id: "hermes",
    name: "Hermes",
    kind: "agent",
    protocol: "MCP",
    tier: "compatible",
    state: "detected",
    detail: "CLI encontrada",
  },
];

export function createDemoSnapshot(state: AccessState = "active"): DesktopSnapshot {
  return {
    schema: "simplicio.desktop-snapshot/v1",
    generatedAt: new Date().toISOString(),
    source: "preview",
    access: {
      state,
      identityKnown: state !== "signed_out",
      entitlementKnown: state === "active" || state === "inactive",
      displayName: state === "signed_out" ? undefined : "Você",
      plan: state === "active" ? "Simplicio MCP · mensal" : undefined,
      renewsAt: state === "active" ? "12 set 2026" : undefined,
    },
    runtime: {
      state: state === "active" ? "healthy" : "offline",
      version: "3.8.35",
      transport: state === "active" ? "sidecar" : "unavailable",
      lastReceiptAt: "agora",
    },
    savings: {
      monthTokens: 1_842_610,
      monthPercent: 71.4,
      estimatedUsd: 42.86,
      cacheHitPercent: 68.2,
      deterministicRuns: 184,
    },
    providers,
    activity: [
      {
        id: "a1",
        title: "Mapa reutilizado antes da edição",
        detail: "Contexto completo permaneceu no Runtime; somente o recibo compacto foi enviado.",
        provider: "Codex",
        savedTokens: 18_420,
        occurredAt: "há 4 min",
        status: "verified",
      },
      {
        id: "a2",
        title: "Validação determinística concluída",
        detail: "Testes e contrato executados no caminho CPU-first.",
        provider: "Runtime",
        savedTokens: 8_910,
        occurredAt: "há 18 min",
        status: "verified",
      },
      {
        id: "a3",
        title: "Conexão aguardando confirmação",
        detail: "A configuração do Claude existe, mas não há sessão ativa comprovada.",
        provider: "Claude Code",
        savedTokens: 0,
        occurredAt: "há 1 h",
        status: "attention",
      },
    ],
  };
}
